# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request closing events but only for the main branch
    pull_request:
      branches: [ main ]
      # types:
      #   - closed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        run: export BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        run: export BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install tox tox-gh-actions
      - name: Release
        run: tox -e release
