# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request closing events but only for the main branch
    pull_request:
      branches: [ main ]
      # types:
      #   - closed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # updated CHANGELOG back to the repository.
      # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
      contents: write
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.BRANCH_NAME }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install tox tox-gh-actions
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - run: echo ${{ secrets.PYPI_TOKEN }} > $HOME/.pypirc
      - name: Release
        run: |
          ls -lart $HOME
          tox -e release
